server:
  port: 8888
  #spring:
  #  datasource:
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    #druid相关配置
  #    druid:
  #      #监控统计拦截的filters
  ##      filters: stat
  #      driver-class-name: oracle.jdbc.OracleDriver
  #      #基本属性
  #      url: jdbc:oracle:thin:@localhost:1521/ORCL
  #      username: scott
  #      password: lcl12345
  #      #配置初始化大小/最小/最大
  #      initial-size: 1
  #      min-idle: 1
  #      max-active: 20
  #      #获取连接等待超时时间
  #      max-wait: 60000
  #      #间隔多久进行一次检测，检测需要关闭的空闲连接
  ##      time-between-eviction-runs-millis: 60000
  #      #一个连接在池中最小生存的时间
  ##      min-evictable-idle-time-millis: 300000
  ##      validation-query: SELECT 'x'
  ##      test-while-idle: true
  ##      test-on-borrow: false
  ##      test-on-return: false
  #
  #      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
  ##      pool-prepared-statements: true
  ##      max-pool-prepared-statement-per-connection-size: 20


  thymeleaf:
      prefix: classpath:/templates/
      check-template-location: true
      suffix: .html
      encoding: utf-8
      cache: false

  aop:
    auto: true
    proxy-target-class: true
#
##  servlet:
##    multipart:
##      max-file-size: 10Mb
##      max-request-size: 100Mb
#
#
#
logging:
  level:
    com.lcl.dao: DEBUG
#
#
#
mybatis:
  mapper-locations: classpath:mapper/*.xml      #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.lcl.model,com.lcl.pojo   # 注意：对应实体类的路径
#
#swagger:
#  show: true
##分页
#pagehelper:
#  helper-dialect: oracle
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
#  retrunPageInfo: check
